[package]
name = "logicworld-badapple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blotter = { git = "https://github.com/agausmann/blotter.rs.git" }